### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by Camilovelag** [MarcoAurelioAntonio/Catalog#17]
## Good day! ⛅
 This issue is created to prepare a Kanban board with a GitHub project for _Ruby Capstone_.

### Changes made 🧰 
- Create and set up a new _repo_.
- Create a new _kanban board_.
- Create cards for every task and assign a user.

Kanban board: https://github.com/users/MarcoAurelioAntonio/projects/5

### Role assignment ✅ 
- Team member # 1 @MarcoAurelioAntonio 
- Team member # 2 @Camilovelag 
- Team member # 3 @Solobarine 

Happy coding! 👏

**Comment by mikethreels** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] for each bullet point in the [requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) there should be a card created in the kanban board
- [x] the work (points) per team member should be evenly divided which it is not right now, please redivide the work so that each team member has more or less the same amount of points.
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by victorokoroji** [comment]
Hi team, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Required Changes ♻️

- [x] KIndly break this down into separate tasks for team member 1 so that they will be easier to keep track of and implement 👇🏽 

![image](https://user-images.githubusercontent.com/63473584/211662554-b2acad4b-df1e-455c-86d5-08fd7bbfa995.png)

- [x] The time estimate was not properly distributed, I can see that `team member 1` had 18 points while `team member 2` had 10 points and `team member 3` has 10 points. The margin is too much. Kindly ensure the point estimates are equal across team members 👍🏽 

_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Camilovelag** [comment]
Changes done! 😄

**Comment by 1GORDON** [comment]
# Status: APPROVED 🟢 

Hi Team ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
